server.port=8080

spring.datasource.url=jdbc:postgresql://postgres:5432/mediot
spring.datasource.username=mediot
spring.datasource.password=mediot
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration